# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_t7C9A6leWjQXWzVH4UX-gfIprS-OlGW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

df = pd.read_csv("/content/Customer_Data.csv")

print("FIRST 5 ROWS")
print(df.head())
print("\nDATASET SHAPE")
print(df.shape)
print("\nDATASET INFO")
print(df.info())
print("\nMISSING VALUES")
print(df.isnull().sum())
print("\nDESCRIPTIVE STATISTICS")
print(df.describe())
df = df.drop_duplicates()

print("\nMISSING VALUES AFTER CLEANING")
print(df.isnull().sum())
print("\nAVERAGE AGE")
print("N/A - 'Age' column not in dataset")
print("\nAVERAGE ANNUAL INCOME")
print("N/A - 'Annual Income (k$)' column not in dataset")
print("\nAVERAGE SPENDING SCORE")
print("N/A - 'Spending Score (1-100)' column not in dataset")
print("\nGender Count visualization commented out: 'Gender' column not in dataset.")
print("\nAge Distribution visualization commented out: 'Age' column not in dataset.")
print("\nIncome vs Spending visualization commented out: relevant columns not in dataset.")
X = df[['BALANCE', 'PURCHASES']]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

wcss = []

for i in range(1, 11):

    kmeans = KMeans(
        n_clusters=i,
        init='k-means++',
        random_state=42
    )

    kmeans.fit(X_scaled)

    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8,5))

plt.plot(range(1,11), wcss, marker='o')

plt.title("Elbow Method (using BALANCE and PURCHASES)")

plt.xlabel("Number of Clusters")

plt.ylabel("WCSS")

plt.show()

kmeans = KMeans(
    n_clusters=5,
    init='k-means++',
    random_state=42
)

df['Cluster'] = kmeans.fit_predict(X_scaled)

plt.figure(figsize=(10,7))

sns.scatterplot(
    x=X.columns[0],
    y=X.columns[1],
    hue='Cluster',
    palette='Set1',
    data=df,
    s=100
)

centers = scaler.inverse_transform(kmeans.cluster_centers_)

plt.scatter(
    centers[:,0],
    centers[:,1],
    s=300,
    c='black',
    marker='X',
    label='Centroids'
)

plt.title("Customer Segmentation (using BALANCE and PURCHASES)")

plt.legend()

plt.show()

print("\nCUSTOMERS IN EACH CLUSTER")

print(df['Cluster'].value_counts())

cluster_analysis = df.groupby('Cluster')[[
    'BALANCE',
    'PURCHASES',
    'CASH_ADVANCE',
    'CREDIT_LIMIT',
    'PAYMENTS'
]].mean()

print("\nCLUSTER ANALYSIS")

print(cluster_analysis)

print("\nINSIGHTS AND RECOMMENDATIONS")

print("""
Note: The following insights and recommendations are based on the original dataset's columns (Age, Annual Income, Spending Score).
To generate relevant insights for the current Customer_Data.csv, a new interpretation based on columns like BALANCE, PURCHASES, CASH_ADVANCE, CREDIT_LIMIT, PAYMENTS would be necessary.

1. High Income + High Spending customers:
   - Target with premium products
   - Provide loyalty rewards

2. High Income + Low Spending customers:
   - Use personalized marketing
   - Offer discounts and recommendations

3. Low Income + High Spending customers:
   - Focus on affordable trendy products

4. Low Income + Low Spending customers:
   - Target during seasonal sales

5. Average customers:
   - Maintain engagement with regular offers
""")